### ISSUE TITLE
pjsip 2.10 pod

### ISSUE THREAD

**Issue by qixin1106** [chebur/pjsip#101]
Can you make a pod with pjsip 2.10 version
Support iOS/macOS platform

**Comment by qixin1106** [comment]
opus does not seem to be available in the macos platform

**Comment by Meonardo** [comment]
> Can you make a pod with pjsip 2.10 version
> Support iOS/macOS platform

You can build your own libs, 
1. check the readme file for building first;
2. then change couple of params in file pjsip.sh 
`PJSIP_URL="https://github.com/pjsip/pjproject/archive/2.10.zip"`;
run build.sh.

**Comment by welljsjs** [comment]
Hi,

yeah I will upgrade to 2.10 in the near future but we're currently both very busy so you might have to wait a little longer unfortunately.
