### ISSUE TITLE
opus-1.3.1 configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by lihj** [chebur/pjsip#106]
Hello，I just run build.sh and get error about opus-1.3.1,how to do? thanks 

Using OpenSSL...
Using opus-1.3.1.tar.gz
Building without ccache
** Compiling armv7
checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for arm-apple-darwin-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-apple-darwin20.2.0
checking host system type... arm-apple-darwin
checking how to print strings... printf
checking for style of include used by make... GNU
checking for arm-apple-darwin-gcc... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/li/Desktop/SIP开发/pod-pjsip/pjsip-master/build/opus/build/src/opus-1.3.1':
configure: error: C compiler cannot create executables
See `config.log' for more details
Configuring for ios i386
Building for ios i386...
make: *** No rule to make target `clean'.  Stop.
Configuring for ios x86_64
Building for ios x86_64...
make: *** No rule to make target `clean'.  Stop.
Configuring for ios armv7
Building for ios armv7...
make: *** No rule to make target `clean'.  Stop.
Configuring for ios armv7s
Building for ios armv7s...
make: *** No rule to make target `clean'.  Stop.
Configuring for ios arm64
Building for ios arm64...
make: *** No rule to make target `clean'.  Stop.
Configuring for macos x86_64
Building for macos x86_64...
make: *** No rule to make target `clean'.  Stop.
Lipo libs... (/var/folders/tq/cchy9skd7zj64gv4g_17djk40000gn/T/lipo.c83lOQoT)
Lipo libs... (/var/folders/tq/cchy9skd7zj64gv4g_17djk40000gn/T/lipo.Xktr1J3P)

**Comment by welljsjs** [comment]
Hi there, could you post the content of your `config.log` file?  Thanks

Also, what platform are you building on? What architecture?

**Comment by lihj** [comment]
> `config.log`

[config.log](https://github.com/chebur/pjsip/files/5909383/config.log)

**Comment by welljsjs** [comment]
Do you have the iPhoneOS12.2 SDK installed?

**Comment by lihj** [comment]
> Do you have the iPhoneOS12.2 SDK installed?

I change to 14.4 and it's OK. But:

li@Li pjsip-master % sh build.sh
Using OpenSSL...
Using OPUS...
Configuring for ios i386
Building for ios i386...
make: *** No rule to make target `clean'.  Stop.
Configuring for ios x86_64
Building for ios x86_64...
make: *** No rule to make target `clean'.  Stop.
Configuring for ios armv7
Building for ios armv7...
make: *** No rule to make target `clean'.  Stop.
Configuring for ios armv7s
Building for ios armv7s...
make: *** No rule to make target `clean'.  Stop.
Configuring for ios arm64
Building for ios arm64...
make: *** No rule to make target `clean'.  Stop.
Configuring for macos x86_64
Building for macos x86_64...
make: *** No rule to make target `clean'.  Stop.
Lipo libs... (/var/folders/tq/cchy9skd7zj64gv4g_17djk40000gn/T/lipo.JrVevQkR)
Lipo libs... (/var/folders/tq/cchy9skd7zj64gv4g_17djk40000gn/T/lipo.WfxoRQDB)

[ios-armv7.log](https://github.com/chebur/pjsip/files/5909720/ios-armv7.log)

**Comment by welljsjs** [comment]
Can you delete the build, clean and run the whole script again? I think it might have messed up sth on the first run.

**Comment by lihj** [comment]
PJSIP_URL="http://www.pjsip.org/release/${PJSIP_VERSION:-2.9}/pjproject-${PJSIP_VERSION:-2.9}.tar.bz2"
this URL is 404, cause the error, I chagne it to https://github.com/pjsip/pjproject/archive/2.10.zip is OK, thanks u very much.
