### ISSUE TITLE
linker error while building

### ISSUE THREAD

**Issue by steveTW** [chebur/pjsip#15]
Hi, I got following error while testing on my IPad

Undefined symbols for architecture armv7:
  "_pjsua_call_get_vid_stream_idx", referenced from:
      -[CallView loadView:withType:] in CallView.o
  "_pjsua_vid_win_get_info", referenced from:
      -[CallView loadView:withType:] in CallView.o
  "_pjsua_vid_win_set_show", referenced from:
      -[CallView loadView:withType:] in CallView.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

can anyone tell me how to fix this?

**Comment by DDany** [comment]
+1.
Using pjsip 2.3 with cocopods, I also faced the same problem.

Undefined symbols for architecture x86_64:
  "_pjsua_call_get_vid_stream_idx", referenced from:
      -[ViewController viewDidLoad] in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

This is very confused. Why?
And no one here can fix this?

**Comment by zsk425** [comment]
@DDany 
You can rebuild it by using build.sh or use my rebuild version here:https://github.com/zsk425/pjsip.

**Comment by chebur** [comment]
it seems that current build does not have support for video calls. will fix it soon
