### ISSUE TITLE
getting linker errors in 2.3.0.7

### ISSUE THREAD

**Issue by jodyscho** [chebur/pjsip#17]
I wasn't sure if this is the correct place for this. I'm getting a few linker errors when trying to move to 2.3.0.7 (2.3.0.6 works great but I'd like to add video to my app).

Undefined symbols for architecture arm64:
  "operator new(unsigned long)", referenced from:
      _WelsCreateDecoder in libopenh264.a(welsDecoderExt.o)
      WelsSVCEnc::CWelsH264SVCEncoder::InitEncoder() in libopenh264.a(welsEncoderExt.o)
      _WelsCreateSVCEncoder in libopenh264.a(welsEncoderExt.o)
      WelsSVCEnc::WelsInitEncoderExt(WelsSVCEnc::TagWelsEncCtx**, WelsSVCEnc::TagWelsSvcCodingParam*) in libopenh264.a(encoder_ext.o)
      WelsDec::CreateWelsTrace(WelsDec::EWelsTraceType, void*) in libopenh264.a(welsCodecTrace.o)
      _CreateVpInterface in libopenh264.a(WelsFrameWork.o)
      nsWelsVP::CreateSpecificVpInterface(IWelsVP**) in libopenh264.a(WelsFrameWork.o)
      ...
  "vtable for __cxxabiv1::__class_type_info", referenced from:
      typeinfo for ISVCDecoder in libopenh264.a(welsDecoderExt.o)
      typeinfo for ISVCEncoder in libopenh264.a(welsEncoderExt.o)
      typeinfo for WelsDec::IWelsTrace in libopenh264.a(welsCodecTrace.o)
      typeinfo for WelsSVCEnc::CMemoryAlign in libopenh264.a(memory_align.o)
      typeinfo for WelsSVCEnc::CWelsPreProcess in libopenh264.a(wels_preprocess.o)
      typeinfo for IWelsVP in libopenh264.a(downsample.o)
      typeinfo for nsWelsVP::CSceneChangeDetectorVideo in libopenh264.a(SceneChangeDetection.o)

**Comment by jodyscho** [comment]
My bad. I had an issue using cocoapods on an older project that had build configurations. My OTHER_LDFLAGS setting was replacing the one generated by cocoapods.

Best

**Comment by chebur** [comment]
So, do you confirm that the video is working properly?

**Comment by jodyscho** [comment]
I haven't tried video yet. I'm upgrading from a much older version of pjsip so I'm still working through iLBC tests and the audio session interruption handler, etc. If I run into issue with video I'll let you know.

Thanks for following up. And for making this a cocoapod. It certainly makes my life a lot easier. :)
