### ISSUE TITLE
openh265 build script not working as expected

### ISSUE THREAD

**Issue by asynnestvedt** [chebur/pjsip#20]
Unarchiving /Users/alan/work/Wickr/vanilla/pjsip/build/openh264/src.download...
Builing for armv7...
Builing for armv7s...
Builing for arm64...
Builing for i386...
asm_inc.asm:63: error: parser: instruction expected
codec/common/x86/cpuid.asm:196: error: symbol `XGETBV' redefined
make: *** [codec/common/x86/cpuid.o] Error 1
asm_inc.asm:63: error: parser: instruction expected
make: *** [codec/encoder/core/x86/coeff.o] Error 1
Builing for x86_64...
nasm: fatal: unrecognised output format `macho64' - use -hf for a list
type `nasm -h' for help
make: *** [codec/common/x86/cpuid.o] Error 1
nasm: fatal: unrecognised output format `macho64' - use -hf for a list
type `nasm -h' for help
make: *** [codec/encoder/core/x86/coeff.o] Error 1
Lipo libs to /Users/alan/work/Wickr/vanilla/pjsip/build/openh264/lib...
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/alan/work/Wickr/vanilla/pjsip/build/openh264/build/i386/lib/libopenh264.a (No such file or directory)

**Comment by chebur** [comment]
Probably your nasm version is too old. See https://github.com/cisco/openh264/issues/1421

**Comment by asynnestvedt** [comment]
nasm is okay. this problem occurs intermittently when I pull down a fresh copy of the repo and build.  Once the error goes away, it stays away.  Not sure what the cause is. I only have once instance of nasm on my OSX 10.9.5 machine.
