### ISSUE TITLE
Build process debug build settings

### ISSUE THREAD

**Issue by asynnestvedt** [chebur/pjsip#21]
Because the build scripts download and unpack PJSIP, overwriting any previously unpacked pjproject directory, you are unable to modify preprocessor defines that are not directly manipulated by the build script, such as PJ_LOG_MAX_LEVEL in pjproject/src/pjlib/include/pj/config_site_sample.h

It would be great if the build script had a flag to build pjsip with debug symbols enabled and expanded macros (CFLAGS += -g3) and raised the PJ_LOG_MAX_LEVEL to 6.  Currently during runtime the max log level is capped at 3 because the runtime setting cannot exceed the value set at build time.

**Comment by chebur** [comment]
I propose to pass a path to a custom config_site.h file as a paramter to pjsip.sh and build.sh scripts. That'll allow custom config directives to be added to default ones while building the pjsip.
