### ISSUE TITLE
linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by cshoaib87** [chebur/pjsip#22]
I have compiled and built openssl, openh264 and pjsip. And I have included all libraries.

Now I am receiving linker errors

ld: warning: directory not found for option '-L../../../../../video/ffmpeg-iphone/build/built/armv7/lib'
ld: warning: directory not found for option '-L/Users/jriyaazpashapasha/Shuhaib/pjsip/build/openh264-new/lib-arm64'
ld: warning: directory not found for option '-L/Users/jriyaazpashapasha/Shuhaib/pjsip/build/openh264-new/lib-armv7'
ld: warning: directory not found for option '-L/Users/jriyaazpashapasha/Shuhaib/pjsip/build/openh264-new/lib-armv7s'
ld: warning: directory not found for option '-L/Users/jriyaazpashapasha/Shuhaib/pjsip/build/openh264-new/lib-i386'
ld: warning: directory not found for option '-L/Users/jriyaazpashapasha/Shuhaib/pjsip/build/openh264-new/lib-x86_64'
ld: warning: ignoring file /Users/jriyaazpashapasha/Shuhaib/pjsip/build/pjproject/src/libyuv-lib/libavfilter.a, file was built for archive which is not the architecture being linked (i386): /Users/jriyaazpashapasha/Shuhaib/pjsip/build/pjproject/src/libyuv-lib/libavfilter.a
ld: warning: ignoring file /Users/jriyaazpashapasha/Shuhaib/pjsip/build/pjproject/src/libyuv-lib/libavresample.a, file was built for archive which is not the architecture being linked (i386): /Users/jriyaazpashapasha/Shuhaib/pjsip/build/pjproject/src/libyuv-lib/libavresample.a
ld: warning: ignoring file /Users/jriyaazpashapasha/Shuhaib/pjsip/build/pjproject/src/libyuv-lib/libavformat.a, file was built for archive which is not the architecture being linked (i386): /Users/jriyaazpashapasha/Shuhaib/pjsip/build/pjproject/src/libyuv-lib/libavformat.a
ld: warning: ignoring file /Users/jriyaazpashapasha/Shuhaib/pjsip/build/pjproject/src/libyuv-lib/libavcodec.a, file was built for archive which is not the architecture being linked (i386): /Users/jriyaazpashapasha/Shuhaib/pjsip/build/pjproject/src/libyuv-lib/libavcodec.a
ld: warning: ignoring file /Users/jriyaazpashapasha/Shuhaib/pjsip/build/pjproject/src/libyuv-lib/libavdevice.a, file was built for archive which is not the architecture being linked (i386): /Users/jriyaazpashapasha/Shuhaib/pjsip/build/pjproject/src/libyuv-lib/libavdevice.a
ld: warning: ignoring file /Users/jriyaazpashapasha/Shuhaib/pjsip/build/pjproject/src/libyuv-lib/libswscale.a, file was built for archive which is not the architecture being linked (i386): /Users/jriyaazpashapasha/Shuhaib/pjsip/build/pjproject/src/libyuv-lib/libswscale.a
ld: warning: ignoring file /Users/jriyaazpashapasha/Shuhaib/pjsip/build/pjproject/src/libyuv-lib/libavutil.a, file was built for archive which is not the architecture being linked (i386): /Users/jriyaazpashapasha/Shuhaib/pjsip/build/pjproject/src/libyuv-lib/libavutil.a
Undefined symbols for architecture i386:
  "vtable for __cxxabiv1::__class_type_info", referenced from:
      typeinfo for ISVCDecoder in libopenh264.a(welsDecoderExt.o)
      typeinfo for ISVCEncoder in libopenh264.a(welsEncoderExt.o)
      typeinfo for WelsDec::IWelsTrace in libopenh264.a(welsCodecTrace.o)
      typeinfo for WelsSVCEnc::CMemoryAlign in libopenh264.a(memory_align.o)
      typeinfo for WelsSVCEnc::CWelsPreProcess in libopenh264.a(wels_preprocess.o)
      typeinfo for IWelsVP in libopenh264.a(WelsFrameWork.o)
      typeinfo for IWelsVP in libopenh264.a(downsample.o)
      ...
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for __cxxabiv1::__si_class_type_info", referenced from:
      typeinfo for WelsDec::CWelsDecoder in libopenh264.a(welsDecoderExt.o)
      typeinfo for WelsSVCEnc::CWelsH264SVCEncoder in libopenh264.a(welsEncoderExt.o)
      typeinfo for WelsDec::CWelsTraceBase in libopenh264.a(welsCodecTrace.o)
      typeinfo for WelsDec::CWelsTraceFile in libopenh264.a(welsCodecTrace.o)
      typeinfo for WelsDec::CWelsCodecTrace in libopenh264.a(welsCodecTrace.o)
      typeinfo for nsWelsVP::CVpFrameWork in libopenh264.a(WelsFrameWork.o)
      typeinfo for nsWelsVP::CDownsampling in libopenh264.a(downsample.o)
      ...
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "operator delete(void*)", referenced from:
      WelsDec::CWelsDecoder::~CWelsDecoder() in libopenh264.a(welsDecoderExt.o)
      _WelsCreateDecoder in libopenh264.a(welsDecoderExt.o)
      WelsSVCEnc::CWelsH264SVCEncoder::InitEncoder() in libopenh264.a(welsEncoderExt.o)
      WelsSVCEnc::CWelsH264SVCEncoder::~CWelsH264SVCEncoder() in libopenh264.a(welsEncoderExt.o)
      WelsSVCEnc::CWelsH264SVCEncoder::~CWelsH264SVCEncoder() in libopenh264.a(welsEncoderExt.o)
      WelsSVCEnc::CWelsH264SVCEncoder::~CWelsH264SVCEncoder() in libopenh264.a(welsEncoderExt.o)
      _WelsCreateSVCEncoder in libopenh264.a(welsEncoderExt.o)
      ...
  "operator new(unsigned long)", referenced from:
      _WelsCreateDecoder in libopenh264.a(welsDecoderExt.o)
      WelsSVCEnc::CWelsH264SVCEncoder::InitEncoder() in libopenh264.a(welsEncoderExt.o)
      _WelsCreateSVCEncoder in libopenh264.a(welsEncoderExt.o)
      WelsSVCEnc::WelsInitEncoderExt(WelsSVCEnc::TagWelsEncCtx**, WelsSVCEnc::TagWelsSvcCodingParam*) in libopenh264.a(encoder_ext.o)
      WelsDec::CreateWelsTrace(WelsDec::EWelsTraceType, void*) in libopenh264.a(welsCodecTrace.o)
      _CreateVpInterface in libopenh264.a(WelsFrameWork.o)
      nsWelsVP::CreateSpecificVpInterface(IWelsVP**) in libopenh264.a(WelsFrameWork.o)
      ...
  "___cxa_pure_virtual", referenced from:
      vtable for WelsDec::CWelsTraceBase in libopenh264.a(welsCodecTrace.o)
  "___gxx_personality_v0", referenced from:
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsDecoderExt.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsEncoderExt.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(encoder_ext.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsCodecTrace.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(memory_align.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(wels_preprocess.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(WelsFrameWork.o)
      ...
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsDecoderExt.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsEncoderExt.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(encoder_ext.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsCodecTrace.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(memory_align.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(wels_preprocess.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(WelsFrameWork.o)
      ...
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsDecoderExt.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsEncoderExt.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(encoder_ext.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsCodecTrace.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(memory_align.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(wels_preprocess.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(WelsFrameWork.o)
      ...
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsDecoderExt.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsEncoderExt.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(encoder_ext.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsCodecTrace.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(memory_align.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(wels_preprocess.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(WelsFrameWork.o)
      ...
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsDecoderExt.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsEncoderExt.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(encoder_ext.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsCodecTrace.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(memory_align.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(wels_preprocess.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(WelsFrameWork.o)
      ...
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsDecoderExt.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsEncoderExt.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(encoder_ext.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsCodecTrace.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(memory_align.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(wels_preprocess.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(WelsFrameWork.o)
      ...
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsDecoderExt.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsEncoderExt.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(encoder_ext.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(welsCodecTrace.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(memory_align.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(wels_preprocess.o)
      Dwarf Exception Unwind Info (__eh_frame) in libopenh264.a(WelsFrameWork.o)
      ...
      ...
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chebur** [comment]
To build openh264 you have to do `brew install nasm`
