### ISSUE TITLE
build.sh throwing openh264 build error

### ISSUE THREAD

**Issue by palash89** [chebur/pjsip#26]
Hi,

While I'm running manual build, I got openh264 install error in all ARCH.log files (armv7, armv7s, arm64,i386,x86_x64). Though, at the end all libraries are generated except libopenh264. The build folder of openh264 only contains libopenh264.a library which was there before making the build.  Now  while using your build command I  got error like this 
```
../src/pjmedia-codec/openh264.cpp
../src/pjmedia-codec/openh264.cpp:35:10: fatal error: 'wels/codec_api.h' file not found
#include <wels/codec_api.h>
         ^
1 error generated.
make[2]: *** [output/pjmedia-codec-arm-apple-darwin9/openh264.o] Error 1
make[1]: *** [libpjmedia-codec-arm-apple-darwin9.a] Error 2
make: *** [all] Error 1

```

This only code I changed was the ```PJSIP_URL```.  I changed it to http://www.pjsip.org/release/2.4.5/pjproject-2.4.5.tar.bz2 accodring the latest version.

Now if I build openh264 library separately for any ARCH, I got lib folder with a .dylib file and the library file and also a include folder where all 3 header files exist in the **Wels** folder.

**Comment by chebur** [comment]
Updated to 2.5.5. To build openh264 you have to `brew install nasm`
