### ISSUE TITLE
Xcode 7 - Bitcode , How to ? 

### ISSUE THREAD

**Issue by chinnasamymca** [chebur/pjsip#27]
When i try to run the app from Xcode 7 it gives me an error, Pjsip is not build with Bitcode. 

How can i enable the Bitcode ?

**Comment by steveTW** [comment]
you should disable it in build setting, not enable it.

**Comment by Rishu** [comment]
any idea, when do we  have bitcode enabled support with this library?

**Comment by chebur** [comment]
Git has a limitation of 100mb per file. I'm afraid with bitcode enabled static libraries could not be stored at the repository.

**Comment by Rishu** [comment]
okay, thanks for your information. Can we have wiki page link from which we can build the pjsip with bitcode enabled flag?

**Comment by kioshimafx** [comment]
@chebur can u upload sh file for build pjsip with bitcode?

**Comment by chebur** [comment]
I would gladly merge a pull request with a bitcode enabled configuration. Please feel free to fork and send me a request. Thanks.

**Comment by rehanslash** [comment]
go to Xcode -> App ->Built Setting -> Built Option then do Enabled Bitcode = NO
it will solve

**Comment by steveTW** [comment]
It seems like disable Bitcode no longer work with version 2.6, trying to get my app archived but so far no luck.

**Comment by GDMiao** [comment]
BItCode is NO
