### ISSUE TITLE
Unsupported transport (PJSIP_EUNSUPTRANSPORT)

### ISSUE THREAD

**Issue by volchanka** [chebur/pjsip#28]
Hello!
I try to use transport type PJSIP_TRANSPORT_TLS, but I'm getting an error:
Unable to generate suitable Contact header for registration: Unsupported transport (PJSIP_EUNSUPTRANSPORT) [status=171060]
 On this page http://trac.pjsip.org/repos/wiki/TLS says that I need to add 
"#define PJ_HAS_SSL_SOCK 1"
 in my config_site.h
How can I do this with pod?

**Comment by chebur** [comment]
There is no way to do this using pod. You have to add the `#define` line to the config header and rebuild the library.
