### ISSUE TITLE
How to play RTP video streaming using this pjsip?

### ISSUE THREAD

**Issue by iraj-wisilica** [chebur/pjsip#29]
Please give me a guideline of playing RTP video streaming using PJSIP library.

**Comment by welljsjs** [comment]
Here you go:
1.  [Guide](https://trac.pjsip.org/repos/wiki/Video_Users_Guide)
2. [Example](https://www.pjsip.org/pjmedia/docs/html/page_pjmedia_samples_vid_streamutil_c.htm)
