### ISSUE TITLE
Lipo doesn't produce FAT libraries

### ISSUE THREAD

**Issue by imaks** [chebur/pjsip#33]
Hi!
Thanks for your great work with building pjsip for iOS, this saves hours of time.

I've found an issue with build script: `build.sh` produces libraries for different iOS architectures and not FAT libraries that include them. I'm not an expert in scripting, but looks like it [grep](https://github.com/chebur/pjsip/blob/master/pjsip.sh#L176) incorrect filename in temp file, searching files like `libpj-armv7-apple-darwin_ios.a` instead of something like `libpj-*`, and this way EXISTS path never executes.

**Comment by chebur** [comment]
I've recently updated a scripts to point to the latest pjsip version, but didn't checked out if the build is running correctly.

Also, I do not have enough time to take care for this project. If you have any success resolving this issue then pull a request please and I'll merge it.

**Comment by chebur** [comment]
Please, checkout updated pod
