### ISSUE TITLE
pjsip libs

### ISSUE THREAD

**Issue by Kamasoutra** [chebur/pjsip#37]
Hi !

During my attempt to upgrade to the latest version, I’m getting the issue of "Undefined symbols for architecture" for both x86_64 and arm64.

After some digging I figured out that compiled libs are missing in the folder "build > pjproject > src > pjsip". I tried the manual compilation, but they are still not generated.

Did something particular change with the upgrade ? Or did I miss something new?

**Comment by chebur** [comment]
Please, roll back to previous version while I'm still preparing the update.

**Comment by Kamasoutra** [comment]
Oh, great ! Let me know if I can help :)

**Comment by chebur** [comment]
Checkout update pod

**Comment by Kamasoutra** [comment]
Works like a charm ! Thanks 👍
