### ISSUE TITLE
Sample integration doesn't compile XCode 7

### ISSUE THREAD

**Issue by thetuyo** [chebur/pjsip#39]
I can't seem to compile the sample integration project.   I did a 'pod install' already, but it seems it can't find the <pjlib.h> file.   Any ideas?

![xcode](https://cloud.githubusercontent.com/assets/9757103/18786590/b0ec93e4-816c-11e6-8a88-b5cbb08d0083.png)

**Comment by chebur** [comment]
Xcode 7 seem to be no longer relevant. Closing the issue.
