### ISSUE TITLE
Need G729 codec

### ISSUE THREAD

**Issue by hlung** [chebur/pjsip#4]
This is not actually an issue. Your lib works pretty well except it doesn't support G729 codec. Could you please guide me on how can I patch the code to include that codec and compile it and create lib files? I'm totally lost here :( I found a patch file here but I don't know how to use it. https://code.google.com/p/siphon/downloads/list

**Comment by MatanGold** [comment]
Would like to know how to add g729 support manually.
Couldn't managed to understand how to use Intel IPP.
(I have an open source code of the codec)

**Comment by gotev** [comment]
I succeded in doing that for Android with PJSIP 2.4.5. I think you can apply the patch also for iOS. Here is my project together with patch instructions: https://github.com/gotev/pjsip-android-builder/tree/master/g729_patch

**Comment by saravanandm** [comment]
Refer my git contribution.https://github.com/saravanandm/pjsip-g729codec It works well, tested with ios app.

**Comment by shehrazjazib** [comment]
Dear all, now i tried to integrate g729 codec with pjsip v2.7, but i failed. So please guide me, what should i do to integrate g729 with latest pjsip . 
Thanks in advance
