### ISSUE TITLE
Opus as default codec

### ISSUE THREAD

**Issue by AleksandarSource** [chebur/pjsip#42]
Hi Thanks a lot for this, it saves a lot of time.
I can see that Opus is enabled. But what setup do I need to make to make PJSIP to offer Opus as available codec on invitation ?
Tnx

**Comment by chebur** [comment]
@cbanta do have any advice on this?

**Comment by cbanta** [comment]
Same as any other codec in pjsip - `pjsua_codec_set_priority`:
http://www.pjsip.org/docs/latest/pjsip/docs/html/group__PJSUA__LIB__MEDIA.htm#gaf6ec502e5898fafc8d697010f44401b2

Something like:
```
pj_str_t opus = pj_str( "opus" );
pjsua_codec_set_priority( &opus, 250 );
```

**Comment by AleksandarSource** [comment]
HI.
I am using your pod and tried this command after I initialize the pjsua. Unfortunately it doesn't return success status. These are the available codec list:
List of codecs:
  130	speex/16000/1
  129	speex/8000/1
  128	speex/32000/1
  128	iLBC/8000/1
  128	GSM/8000/1
  128	PCMU/8000/1
  128	PCMA/8000/1
  128	G722/16000/1

I also tried to init Opus with these commands:

pjmedia_endpt *mept;
mept = pjsua_get_pjmedia_endpt();
pjmedia_codec_opus_init(mept);

but it gives an error: 
Undefined symbols for architecture arm64:
  "_pjmedia_codec_opus_init"

Is there something else that should be done to use Opus with this pod ? Should be there some change in configuration when building the PJSIP to support Opus ?

Thank you

**Comment by AleksandarSource** [comment]
Can you reproduce the same output ? For example on a new clean project with just the pod installed ?
Tnx

**Comment by welljsjs** [comment]
Please file a new bug report if the issue persists.
