### ISSUE TITLE
Pod not updated to latest release in Cocoapods' spec repo

### ISSUE THREAD

**Issue by nadavhart** [chebur/pjsip#43]
Hey,

First of all - fantastic project, thank you! 🙏 

The pod available in this repo is for release 2.5.5.3, while the pod in the main [Cocoapods spec repo](https://github.com/CocoaPods/Specs/tree/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/9/4/9/pjsip) is 2.5.5.2, which doesn't include OPUS. Any chance for an update?

Thanks

**Comment by nadavhart** [comment]
@chebur @cbanta Any plans on this front? Would be happy to help if necessary

**Comment by chebur** [comment]
I'll take a look at it soon

**Comment by chebur** [comment]
Done at #47. Cocopods spec is also updated.
