### ISSUE TITLE
Linking Error

### ISSUE THREAD

**Issue by Xedart** [chebur/pjsip#45]
My project, which includes pjsip compiles well for all possible simulators but I have linking issue when try compile it for real device target.

Here is my error message:

clang: error: linker command failed with exit code 1 (use -v to see invocation)

Anybody knows something about what I can do?

**Comment by Xedart** [comment]
Ok, for anyone who may be interested, i have finally figured this problem out.
The reason of linking error was the new technique used by apple since iOS 9.0 – App Thinning.
In particular, there is option, called “enable bitcode” that is applied to any project by default ( here the link to apple docs: https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html ). This produces this error, because: “f you provide bitcode, all apps and frameworks in the app bundle (all targets in the project) need to include bitcode. ” – from apple docs.
The problem is that PJSIP creates static libs which don’t support this bitcode feature.

So, in order to deal with this problem, just disable “enable bitcode” in project settings!
I am surprised that I wasn’t able to find this solution anywhere.

Hope it will help someone!

**Comment by mikle94** [comment]
@Xedart Thank you for sharing the solution. Helped me with same error!
