### ISSUE TITLE
Podfile issue

### ISSUE THREAD

**Issue by telecomsxchange** [chebur/pjsip#54]
As per your instructions we added pod 'pjsip' in the Podfile.

After running pod install, we get this error:

[!] The dependency `pjsip` is not used in any concrete target.

**Comment by GDMiao** [comment]
@telecomsxchange  like this
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'xxxDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PJSIPSwiftDemo
	pod 'pjsip'
end

**Comment by mayankbaiswar-CSE** [comment]
you have to add target into the podfile.
for eg.- 
target 'ipjsystest' do
   pod 'pjsip'
end

**Comment by chebur** [comment]
i think this fixes it
