### ISSUE TITLE
拨打电话 崩溃

### ISSUE THREAD

**Issue by 9527001** [chebur/pjsip#56]
真机：
20:28:50.661 coreaudio_dev. !...core audio stream started
CRMSystemClient(2611,0x1b5977b80) malloc: *** mach_vm_map(size=4295065600) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
20:28:50.673       except.c  .!!!FATAL: unhandled exception PJLIB/No memory!

模拟器
probably  re-registering existing thread  IOS

**Comment by welljsjs** [comment]
Care to elaborate?

https://translate.google.de
