### ISSUE TITLE
 example demo 运行 崩溃

### ISSUE THREAD

**Issue by GDMiao** [chebur/pjsip#57]
example demo pod install 后，运行 崩溃。
2018-01-04 14:17:23.916596+0800 ipjsystest[38600:425988] +[CATransaction synchronize] called within transaction
2018-01-04 14:17:24.359006+0800 ipjsystest[38600:425988] *** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3698.33.6/UIApplication.m:3529
2018-01-04 14:17:24.366856+0800 ipjsystest[38600:425988] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of application launch'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001053d312b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000104a67f41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001053d82f2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000101c2ad69 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x00000001021ae051 -[UIApplication _runWithMainScene:transitionContext:completion:] + 3102
	5   UIKit                               0x00000001025776f8 __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 924
	6   UIKit                               0x000000010294d4c8 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	7   UIKit                               0x00000001025772f1 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 249
	8   UIKit                               0x0000000102577b6b -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 696
	9   UIKit                               0x0000000102ef5a69 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 262
	10  UIKit                               0x0000000102ef5922 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 444
	11  UIKit                               0x0000000102bd29c8 __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 221
	12  UIKit                               0x0000000102dd1b06 _performActionsWithDelayForTransitionContext + 100
	13  UIKit                               0x0000000102bd288b -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 231
	14  UIKit                               0x000000010294cb25 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	15  UIKit                               0x00000001021ac36a -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 523
	16  UIKit                               0x0000000102787605 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 369
	17  FrontBoardServices                  0x000000010b58acc0 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 338
	18  FrontBoardServices                  0x000000010b5937b5 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 235
	19  libdispatch.dylib                   0x0000000105c3b33d _dispatch_client_callout + 8
	20  libdispatch.dylib                   0x0000000105c409f3 _dispatch_block_invoke_direct + 592
	21  FrontBoardServices                  0x000000010b5bf498 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	22  FrontBoardServices                  0x000000010b5bf14e -[FBSSerialQueue _performNext] + 464
	23  FrontBoardServices                  0x000000010b5bf6bd -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	24  CoreFoundation                      0x0000000105376101 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	25  CoreFoundation                      0x0000000105415f71 __CFRunLoopDoSource0 + 81
	26  CoreFoundation                      0x000000010535aa19 __CFRunLoopDoSources0 + 185
	27  CoreFoundation                      0x0000000105359fff __CFRunLoopRun + 1279
	28  CoreFoundation                      0x0000000105359889 CFRunLoopRunSpecific + 409
	29  GraphicsServices                    0x0000000107b469c6 GSEventRunModal + 62
	30  UIKit                               0x00000001021af5d6 UIApplicationMain + 159
	31  ipjsystest                          0x0000000100277fa1 main + 97
	32  libdyld.dylib                       0x0000000105cb7d81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by GDMiao** [comment]
崩溃了

**Comment by 9527001** [comment]
我这里运不崩溃 测试的分机号有的可以拨通，有的不可以 。兄弟可以给一个分机号，测试一下哈

**Comment by GDMiao** [comment]
demo 我放弃了， 我用的 linphone的 sip.linphone.org 测试的。
运行真机报错 arm 64 ， 你运行时log 版本是多少啊？我这显示2.6.
pod 版本 log打印是 2.6， 不是更新到 2.7.1 了吗？
真机运行报错，模拟器可以运行。是版本的问题吗？
Showing All Issues
ld: '/Users/weci/Desktop/MyDemo/PJSIPSwiftDemo/Pods/pjsip/build/pjproject/src/pjmedia/lib/libpjmedia-videodev-apple-darwin_ios.a(ios_opengl_dev.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/weci/Desktop/MyDemo/PJSIPSwiftDemo/Pods/pjsip/build/pjproject/src/pjmedia/lib/libpjmedia-videodev-apple-darwin_ios.a' for architecture arm64

**Comment by GDMiao** [comment]
有联系方式吗 ？可以加个QQ 聊聊，交流一下呗。

**Comment by GDMiao** [comment]
@9527001  你集成 jpsip 拨号可以啊？我集成的这个 拨号失败，拨拨通？ 不知道为什么？

**Comment by 9527001** [comment]
我这里的问题是服务的sip版本过低，把版本降到2.5就OK了

**Comment by 9527001** [comment]
@GDMiao  但是出现了新的问题 就是真机会提示获取相机权限，很烦人   我的qq1508574114

**Comment by GDMiao** [comment]
我自己编译的 2.7.1 ，可以拨号，现在就是ipv6只能登录，其他功能不是很好使。ipv4 正常，我就是按教程搭的，没做视频 ，只做通话了。

**Comment by mayankbaiswar-CSE** [comment]
mine is crashing with this error

>  *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of application launch'

any idea what to do?

**Comment by anuranBarman** [comment]
> mine is crashing with this error
> 
> > *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of application launch'
> 
> any idea what to do?

replace your applicationDidLaunchWithOptions with this
```
- (void)applicationDidFinishLaunching:(UIApplication *)application {    
    
    // Override point for customization after app launch
    //[window addSubview:[navigationController view]];
    [window setRootViewController:navigationController];
    [window makeKeyAndVisible];
}
```

This will fix your problem.
