### ISSUE TITLE
真机运行 报错 arm64

### ISSUE THREAD

**Issue by GDMiao** [chebur/pjsip#58]
pod 版本 log打印是 2.6， 不是更新到 2.7.1 了吗？
真机运行报错，模拟器可以运行。是版本的问题吗？
Showing All Issues
ld: '/Users/weci/Desktop/MyDemo/PJSIPSwiftDemo/Pods/pjsip/build/pjproject/src/pjmedia/lib/libpjmedia-videodev-apple-darwin_ios.a(ios_opengl_dev.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/weci/Desktop/MyDemo/PJSIPSwiftDemo/Pods/pjsip/build/pjproject/src/pjmedia/lib/libpjmedia-videodev-apple-darwin_ios.a' for architecture arm64

**Comment by welljsjs** [comment]
Care to elaborate?

https://translate.google.de
