### ISSUE TITLE
2.7.1 release?

### ISSUE THREAD

**Issue by armandzwan** [chebur/pjsip#61]
When I use Cocoapods, the latest version is 2.6
When will 2.7.1 be released?

**Comment by freegor** [comment]
I confirm, pj_get_version() returns 2.6, but last commit name is "PJSIP 2.7.1 Build".

**Comment by armandzwan** [comment]
Bump, no?

**Comment by nazrul-capanicus** [comment]
Plz release pjsip 2.7.2 with nat64 support

**Comment by girijeshkumar2007** [comment]
Any update on nat64 support

**Comment by cloudface** [comment]
Is there any update on this? I'm having the same issue. I need to use features from pjsip 2.7.1 but the pod only gives me 2.6.

**Comment by cloudface** [comment]
I just learned that you can also just reference a specific git commit in your podfile. So even if the pod with 2.7.1 was not published, you can install it in your project using the following:

`pod 'pjsip', :git => 'https://github.com/chebur/pjsip.git', :commit => '0bd3ff6' `

**Comment by armandzwan** [comment]
Thanks! That's a good one. Going to try it.

**Comment by armandzwan** [comment]
Tested, and it works. I see PJSip 2.7.2 is released. Here we go again.

**Comment by armandzwan** [comment]
PJSip 2.8 is released...

**Comment by chebur** [comment]
Merged the update. Updating podspec soon
