### ISSUE TITLE
Liking error FFMPEG

### ISSUE THREAD

**Issue by steveTW** [chebur/pjsip#63]
I'm using XCode 8.3.2, IOS version 10.3 building v2.6 and having issue when calling pjmedia_codec_ffmpeg_vid_init().

Undefined symbols for architecture armv7:
  "_pjmedia_codec_ffmpeg_vid_init", referenced from:
      -[AppDelegate registeration] in AppDelegate.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by welljsjs** [comment]
You can simply reconfigure with `--disable-ffmpeg` and rebuild the libraries. Check the logs to see whether your configuration was successful.
