### ISSUE TITLE
PJSIP_EUNSUPTRANSPORT

### ISSUE THREAD

**Issue by JMVivue** [chebur/pjsip#65]
在iOS上登录sipServer 的时候, 遇到PJSIP_EUNSUPTRANSPORT错误, 
Unable to generate suitable Contact header for registration: Unsupported transport (PJSIP_EUNSUPTRANSPORT)
试过 tcp /udp 都不行 ,
编译的最新 2.7.2 的版本;
请问有什么好的建议么, 谢谢了

**Comment by shwetadodiya** [comment]
Is this solved? I am having the same issue

**Comment by armandzwan** [comment]
Are you using IPv6?

**Comment by welljsjs** [comment]
Does this issue still occur after upgrading to the latest version?

If it does, please provide more information and we'll look into it and perhaps reopen this issue.
