### ISSUE TITLE
linking issue after adding in your project

### ISSUE THREAD

**Issue by girijeshkumar2007** [chebur/pjsip#66]
Undefined symbols for architecture arm64:
  "_WebRtcAec_Process", referenced from:
      _webrtc_aec_cancel_echo in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
  "_WebRtcAec_BufferFarend", referenced from:
      _webrtc_aec_cancel_echo in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
  "_WebRtcNs_Process", referenced from:
      _webrtc_aec_cancel_echo in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
  "_WebRtcAec_Create", referenced from:
      _webrtc_aec_create in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
  "_WebRtcAec_Init", referenced from:
      _webrtc_aec_create in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
      _webrtc_aec_reset in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
  "_WebRtcAec_aec_core", referenced from:
      _webrtc_aec_create in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
  "_WebRtcNs_Free", referenced from:
      _webrtc_aec_create in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
      _webrtc_aec_destroy in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
  "_ABGRToARGB", referenced from:
      _conv_to_bgra in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_I422ToARGB", referenced from:
      _conv_to_bgra in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_RGB24ToI420", referenced from:
      _conv_to_i420 in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_WebRtcAec_set_config", referenced from:
      _set_config in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
  "_ARGBToI420", referenced from:
      _conv_from_bgra in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
      _conv_to_i420 in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_YUY2ToI420", referenced from:
      _conv_to_i420 in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_UYVYToI420", referenced from:
      _conv_to_i420 in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_WelsCreateSVCEncoder", referenced from:
      oh264_alloc_codec(pjmedia_vid_codec_factory*, pjmedia_vid_codec_info const*, pjmedia_vid_codec**) in libpjmedia-codec-apple-darwin_ios.a(openh264.o)
  "_I420ToABGR", referenced from:
      _conv_from_i420 in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_ARGBToRGB24", referenced from:
      _conv_from_bgra in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_WebRtcAec_Free", referenced from:
      _webrtc_aec_create in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
      _webrtc_aec_destroy in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
  "_YUY2ToARGB", referenced from:
      _conv_to_bgra in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_UYVYToARGB", referenced from:
      _conv_to_bgra in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_ARGBToYUY2", referenced from:
      _conv_from_bgra in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_ARGBToUYVY", referenced from:
      _conv_from_bgra in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_WebRtcNs_Analyze", referenced from:
      _webrtc_aec_cancel_echo in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
  "_ABGRToI420", referenced from:
      _conv_to_i420 in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_ARGBScale", referenced from:
      _conv_from_bgra in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_I420ToRGB24", referenced from:
      _conv_from_i420 in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_WelsDestroySVCEncoder", referenced from:
      oh264_alloc_codec(pjmedia_vid_codec_factory*, pjmedia_vid_codec_info const*, pjmedia_vid_codec**) in libpjmedia-codec-apple-darwin_ios.a(openh264.o)
      oh264_dealloc_codec(pjmedia_vid_codec_factory*, pjmedia_vid_codec*) in libpjmedia-codec-apple-darwin_ios.a(openh264.o)
  "_pjmedia_vid_dev_subsys_shutdown", referenced from:
      _pjsua_vid_subsys_destroy in libpjsua-apple-darwin_ios.a(pjsua_vid.o)
  "_ARGBToI422", referenced from:
      _conv_from_bgra in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_I420ToYUY2", referenced from:
      _conv_from_i420 in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_I420ToUYVY", referenced from:
      _conv_from_i420 in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_I420ToARGB", referenced from:
      _conv_from_i420 in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
      _conv_to_bgra in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_WebRtcAec_get_error_code", referenced from:
      _print_webrtc_aec_error in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
  "_I420ToI422", referenced from:
      _conv_from_i420 in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_I420Scale", referenced from:
      _conv_from_i420 in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_WebRtcAec_enable_delay_agnostic", referenced from:
      _webrtc_aec_create in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
  "_ARGBToABGR", referenced from:
      _conv_from_bgra in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_WebRtcNs_Create", referenced from:
      _webrtc_aec_create in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
  "_RGB24ToARGB", referenced from:
      _conv_to_bgra in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_WelsCreateDecoder", referenced from:
      oh264_alloc_codec(pjmedia_vid_codec_factory*, pjmedia_vid_codec_info const*, pjmedia_vid_codec**) in libpjmedia-codec-apple-darwin_ios.a(openh264.o)
      oh264_codec_open(pjmedia_vid_codec*, pjmedia_vid_codec_param*) in libpjmedia-codec-apple-darwin_ios.a(openh264.o)
  "_I422ToI420", referenced from:
      _conv_to_i420 in libpjmedia-apple-darwin_ios.a(converter_libyuv.o)
  "_pjmedia_vid_dev_subsys_init", referenced from:
      _pjsua_vid_subsys_init in libpjsua-apple-darwin_ios.a(pjsua_vid.o)
  "_WebRtcNs_Init", referenced from:
      _webrtc_aec_create in libpjmedia-apple-darwin_ios.a(echo_webrtc.o)
  "_WelsDestroyDecoder", referenced from:
      oh264_alloc_codec(pjmedia_vid_codec_factory*, pjmedia_vid_codec_info const*, pjmedia_vid_codec**) in libpjmedia-codec-apple-darwin_ios.a(openh264.o)
      oh264_dealloc_codec(pjmedia_vid_codec_factory*, pjmedia_vid_codec*) in libpjmedia-codec-apple-darwin_ios.a(openh264.o)
ld: symbol(s) not found for architecture arm64

**Comment by welljsjs** [comment]
Could you format you code by using \` backticks, please?
What version are you working with?
