### ISSUE TITLE
Dynamic change video resolution, video calls, initiate reinvite, cause a deadlock

### ISSUE THREAD

**Issue by a42279395** [chebur/pjsip#68]
Dynamic change video resolution, video calls, initiate reinvite, cause a deadlock

16:27:23.090           pjsua_call.c !Sending re-INVITE on call 0
16:27:23.090           pjsua_call.c !.acquire_call on call 0
16:27:23.090           pjsua_call.c  .pjsua_call_media_is_changing on call 0
16:27:23.090           pjsua_call.c  .x1 on call 0
16:27:23.090          pjsua_media.c  .Call 0: deinitializing media..
16:27:23.091          pjsua_media.c  ...Media stream call00:0 is destroyed
16:27:23.091            pjsua_vid.c  ...Stopping video stream..
16:27:23.186           darwin_dev.m  ....Stopping Darwin video stream
16:27:23.294            pjsua_vid.c  ....dec_vid_win begin..
16:27:23.295            pjsua_vid.c  ....Window 1: destroying..
16:27:23.295             vid_port.c  .....Closing 前置相机..
16:27:23.297            pjsua_vid.c  ....dec_vid_win end..

**Comment by a42279395** [comment]
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x0000000183ee5610 libsystem_kernel.dylib`__semwait_signal + 8
    frame #1: 0x000000018408b34c libsystem_pthread.dylib`_pthread_join$VARIANT$armv81 + 624
    frame #2: 0x0000000103d1bc44 HXHY`pj_thread_join + 60
    frame #3: 0x0000000103c1aab8 HXHY`pjmedia_clock_stop + 44
    frame #4: 0x0000000103c34f20 HXHY`pjmedia_vid_port_stop + 32
    frame #5: 0x0000000103d1487c HXHY`pjsua_vid_stop_stream + 516
    frame #6: 0x0000000103d0d5bc HXHY`stop_media_stream + 156
    frame #7: 0x0000000103d0c3d4 HXHY`pjsua_media_channel_deinit + 204
    frame #8: 0x0000000103cff578 HXHY`apply_call_setting + 60
    frame #9: 0x0000000103d02330 HXHY`pjsua_call_reinvite2 + 424
    frame #10: 0x0000000103d02178 HXHY`pjsua_call_reinvite + 140
    frame #11: 0x0000000103332838 HXHY`-[HXPJSIPBaseManager keepAlive](self=0x00000001d000ae40, _cmd="keepAlive") at HXPJSIPBaseManager.m:1247
    frame #12: 0x0000000103332610 HXHY`-[HXPJSIPBaseManager pjCallUpdateWithCallid:](self=0x00000001d000ae40, _cmd="pjCallUpdateWithCallid:", callid=0) at HXPJSIPBaseManager.m:1216
    frame #13: 0x0000000102b001d0 HXHY`-[HXSIPP2PViewController btnViewClickZoomBtn:](self=0x000000014b020400, _cmd="btnViewClickZoomBtn:", is=YES) at HXSIPP2PViewController.m:1110
    frame #14: 0x0000000102b084c8 HXHY`__40-[HXSIPP2PViewController controlBtnView]_block_invoke.831(.block_descriptor=0x00000001cc05b7e0, is=YES) at HXSIPP2PViewController.m:1748
    frame #15: 0x000000010280fc8c HXHY`-[HXSIPP2PControlBtnView clickBtn:](self=0x0000000147d1b0b0, _cmd="clickBtn:", btn=0x0000000147d1c2d0) at HXSIPP2PControlBtnView.m:258
    frame #16: 0x000000018e1ca64c UIKit`-[UIApplication sendAction:to:from:forEvent:] + 96
    frame #17: 0x000000018e2eb870 UIKit`-[UIControl sendAction:to:forEvent:] + 80
    frame #18: 0x000000018e1d0700 UIKit`-[UIControl _sendActionsForEvents:withEvent:] + 440
    frame #19: 0x000000018e3061a8 UIKit`-[UIControl touchesEnded:withEvent:] + 572
    frame #20: 0x000000018e24d9e0 UIKit`-[UIWindow _sendTouchesForEvent:] + 2428
    frame #21: 0x000000018e242890 UIKit`-[UIWindow sendEvent:] + 3160
    frame #22: 0x000000018e2411d0 UIKit`-[UIApplication sendEvent:] + 340
    frame #23: 0x000000018ea22d1c UIKit`__dispatchPreprocessedEventFromEventQueue + 2340
    frame #24: 0x000000018ea252c8 UIKit`__handleEventQueueInternal + 4744
    frame #25: 0x000000018ea1e368 UIKit`__handleHIDEventFetcherDrain + 152
    frame #26: 0x0000000184407404 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
    frame #27: 0x0000000184406c2c CoreFoundation`__CFRunLoopDoSources0 + 276
    frame #28: 0x000000018440479c CoreFoundation`__CFRunLoopRun + 1204
    frame #29: 0x0000000184324da8 CoreFoundation`CFRunLoopRunSpecific + 552
    frame #30: 0x0000000186309020 GraphicsServices`GSEventRunModal + 100
    frame #31: 0x000000018e341758 UIKit`UIApplicationMain + 236
    frame #32: 0x0000000102aa0264 HXHY`main(argc=1, argv=0x000000016d6bb870) at main.m:14
    frame #33: 0x0000000183db5fc0 libdyld.dylib`start + 4
  thread #6, name = 'gputools.smt_poll.0x1cc032460'
    frame #0: 0x0000000183ee5610 libsystem_kernel.dylib`__semwait_signal + 8
    frame #1: 0x0000000183dfe12c libsystem_c.dylib`nanosleep + 212
    frame #2: 0x0000000183dfe04c libsystem_c.dylib`usleep + 64
    frame #3: 0x000000010617a2bc GPUToolsCore`smt_poll_thread_entry(void*) + 136
    frame #4: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #5: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #6: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #7, name = 'gputools.smt_poll.0x1c40326a0'
    frame #0: 0x0000000183ee5610 libsystem_kernel.dylib`__semwait_signal + 8
    frame #1: 0x0000000183dfe12c libsystem_c.dylib`nanosleep + 212
    frame #2: 0x0000000183dfe04c libsystem_c.dylib`usleep + 64
    frame #3: 0x000000010617a2bc GPUToolsCore`smt_poll_thread_entry(void*) + 136
    frame #4: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #5: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #6: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #8, name = 'com.apple.uikit.eventfetch-thread'
    frame #0: 0x0000000183ec3e08 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x0000000183ec3c80 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x0000000184406e40 CoreFoundation`__CFRunLoopServiceMachPort + 196
    frame #3: 0x0000000184404908 CoreFoundation`__CFRunLoopRun + 1568
    frame #4: 0x0000000184324da8 CoreFoundation`CFRunLoopRunSpecific + 552
    frame #5: 0x0000000184d99674 Foundation`-[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
    frame #6: 0x0000000184d9951c Foundation`-[NSRunLoop(NSRunLoop) runUntilDate:] + 148
    frame #7: 0x000000018e026768 UIKit`-[UIEventFetcher threadMain] + 136
    frame #8: 0x0000000184ea9efc Foundation`__NSThread__start__ + 1040
    frame #9: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #10: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #11: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #15, name = 'com.apple.CFSocket.private'
    frame #0: 0x0000000183ee5538 libsystem_kernel.dylib`__select + 8
    frame #1: 0x000000018440f378 CoreFoundation`__CFSocketManager + 644
    frame #2: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #3: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #4: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #18, name = 'MainRunloopMonitor'
    frame #0: 0x0000000183ec3e5c libsystem_kernel.dylib`semaphore_timedwait_trap + 8
    frame #1: 0x00000001060c12a0 libdispatch.dylib`_dispatch_sema4_timedwait + 60
    frame #2: 0x00000001060c1a18 libdispatch.dylib`_dispatch_semaphore_wait_slow + 72
    frame #3: 0x00000001037f44a8 HXHY`-[BLYMainRunloopMonitorManager monitorThreadRun] + 212
    frame #4: 0x0000000184ea9efc Foundation`__NSThread__start__ + 1040
    frame #5: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #6: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #7: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #20, name = 'com.apple.NSURLConnectionLoader'
    frame #0: 0x0000000183ec3e08 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x0000000183ec3c80 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x0000000184406e40 CoreFoundation`__CFRunLoopServiceMachPort + 196
    frame #3: 0x0000000184404908 CoreFoundation`__CFRunLoopRun + 1568
    frame #4: 0x0000000184324da8 CoreFoundation`CFRunLoopRunSpecific + 552
    frame #5: 0x0000000184c326e0 CFNetwork`-[__CoreSchedulingSetRunnable runForever] + 220
    frame #6: 0x0000000184ea9efc Foundation`__NSThread__start__ + 1040
    frame #7: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #8: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #9: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #21
    frame #0: 0x0000000103d20f3c HXHY`pj_list_erase
    frame #1: 0x0000000103c3e390 HXHY`session_info_reset + 36
    frame #2: 0x0000000103c3bb94 HXHY`frame_buffer_reset + 24
    frame #3: 0x0000000103c3cd68 HXHY`jitter_buffer_insert_packet + 1000
    frame #4: 0x0000000103c3b4b8 HXHY`jitter_buffer_interface_insert_packet + 208
    frame #5: 0x0000000103c35eec HXHY`on_rx_rtp + 884
    frame #6: 0x0000000103c2f83c HXHY`srtp_rtp_cb + 68
    frame #7: 0x0000000103c311e4 HXHY`on_rx_rtp + 572
    frame #8: 0x0000000103d192e4 HXHY`ioqueue_dispatch_read_event + 748
    frame #9: 0x0000000103d1abbc HXHY`pj_ioqueue_poll + 704
    frame #10: 0x0000000103c20a24 HXHY`worker_proc + 64
    frame #11: 0x0000000103d1ba8c HXHY`thread_main + 84
    frame #12: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #13: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #14: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #22
    frame #0: 0x0000000183ee5538 libsystem_kernel.dylib`__select + 8
    frame #1: 0x0000000103d1e600 HXHY`pj_sock_select + 84
    frame #2: 0x0000000103d1a9c0 HXHY`pj_ioqueue_poll + 196
    frame #3: 0x0000000103b7e238 HXHY`pjsip_endpt_handle_events2 + 140
    frame #4: 0x0000000103d05108 HXHY`worker_thread + 68
    frame #5: 0x0000000103d1ba8c HXHY`thread_main + 84
    frame #6: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #7: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #8: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #23, name = 'com.apple.CoreMotion.MotionThread'
    frame #0: 0x0000000183ec3e08 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x0000000183ec3c80 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x0000000184406e40 CoreFoundation`__CFRunLoopServiceMachPort + 196
    frame #3: 0x0000000184404908 CoreFoundation`__CFRunLoopRun + 1568
    frame #4: 0x0000000184324da8 CoreFoundation`CFRunLoopRunSpecific + 552
    frame #5: 0x0000000184374b28 CoreFoundation`CFRunLoopRun + 116
    frame #6: 0x00000001899199dc CoreMotion`___lldb_unnamed_symbol2852$$CoreMotion + 1120
    frame #7: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #8: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #9: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #24
    frame #0: 0x0000000183ee5610 libsystem_kernel.dylib`__semwait_signal + 8
    frame #1: 0x0000000183dfe12c libsystem_c.dylib`nanosleep + 212
    frame #2: 0x0000000183e66ef4 libsystem_c.dylib`sleep + 44
    frame #3: 0x0000000103811bb0 HXHY`___lldb_unnamed_symbol15$$HXHY + 732
    frame #4: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #5: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #6: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #30
    frame #0: 0x0000000183ee6f84 libsystem_kernel.dylib`sem_wait + 8
    frame #1: 0x0000000103d1c484 HXHY`pj_sem_wait + 32
    frame #2: 0x0000000103c21bb0 HXHY`event_worker_thread + 228
    frame #3: 0x0000000103d1ba8c HXHY`thread_main + 84
    frame #4: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #5: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #6: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #31
    frame #0: 0x0000000184083b04 libsystem_pthread.dylib`start_wqthread
  thread #32, name = 'AVAudioSession Notify Thread'
    frame #0: 0x0000000183ec3e08 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x0000000183ec3c80 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x0000000184406e40 CoreFoundation`__CFRunLoopServiceMachPort + 196
    frame #3: 0x0000000184404908 CoreFoundation`__CFRunLoopRun + 1568
    frame #4: 0x0000000184324da8 CoreFoundation`CFRunLoopRunSpecific + 552
    frame #5: 0x0000000189e1e398 AVFAudio`GenericRunLoopThread::Entry(void*) + 164
    frame #6: 0x0000000189e487a8 AVFAudio`CAPThread::Entry(CAPThread*) + 88
    frame #7: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #8: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #9: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #36, name = 'com.apple.coreaudio.AQClient'
    frame #0: 0x0000000183ec3e08 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x0000000183ec3c80 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x0000000184406e40 CoreFoundation`__CFRunLoopServiceMachPort + 196
    frame #3: 0x0000000184404908 CoreFoundation`__CFRunLoopRun + 1568
    frame #4: 0x0000000184324da8 CoreFoundation`CFRunLoopRunSpecific + 552
    frame #5: 0x000000018819d6f4 AudioToolbox`GenericRunLoopThread::Entry(void*) + 164
    frame #6: 0x00000001883c379c AudioToolbox`CAPThread::Entry(CAPThread*) + 88
    frame #7: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #8: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #9: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #46, name = 'AURemoteIO::IOThread'
    frame #0: 0x0000000183ec3e08 libsystem_kernel.dylib`mach_msg_trap + 8
    frame #1: 0x0000000183ec3c80 libsystem_kernel.dylib`mach_msg + 72
    frame #2: 0x000000018805bd38 AudioToolbox`AURemoteIO::IOThread::Run() + 260
    frame #3: 0x00000001880605bc AudioToolbox`AURemoteIO::IOThread::Entry(void*) + 156
    frame #4: 0x00000001883c379c AudioToolbox`CAPThread::Entry(CAPThread*) + 88
    frame #5: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #6: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #7: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #47
    frame #0: 0x0000000183ee5610 libsystem_kernel.dylib`__semwait_signal + 8
    frame #1: 0x0000000183dfe12c libsystem_c.dylib`nanosleep + 212
    frame #2: 0x0000000183dfe04c libsystem_c.dylib`usleep + 64
    frame #3: 0x0000000103d1bcf0 HXHY`pj_thread_sleep + 36
    frame #4: 0x0000000103c1a918 HXHY`clock_thread + 164
    frame #5: 0x0000000103d1ba8c HXHY`thread_main + 84
    frame #6: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #7: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #8: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #48
    frame #0: 0x0000000183ee50f4 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x000000018408bed8 libsystem_pthread.dylib`_pthread_cond_wait$VARIANT$armv81 + 628
    frame #2: 0x0000000184dc3698 Foundation`-[NSObject(NSThreadPerformAdditions) performSelector:onThread:withObject:waitUntilDone:modes:] + 760
    frame #3: 0x0000000184dc3318 Foundation`-[NSObject(NSThreadPerformAdditions) performSelectorOnMainThread:withObject:waitUntilDone:] + 144
    frame #4: 0x0000000103c942a8 HXHY`iosgl_stream_put_frame + 52
    frame #5: 0x0000000103c347cc HXHY`dec_clock_cb + 92
    frame #6: 0x0000000103c1a93c HXHY`clock_thread + 200
    frame #7: 0x0000000103d1ba8c HXHY`thread_main + 84
    frame #8: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #9: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #10: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #50
    frame #0: 0x0000000183ee5610 libsystem_kernel.dylib`__semwait_signal + 8
    frame #1: 0x0000000183dfe12c libsystem_c.dylib`nanosleep + 212
    frame #2: 0x0000000183dfe04c libsystem_c.dylib`usleep + 64
    frame #3: 0x0000000103d1bcf0 HXHY`pj_thread_sleep + 36
    frame #4: 0x0000000103c1a918 HXHY`clock_thread + 164
    frame #5: 0x0000000103d1ba8c HXHY`thread_main + 84
    frame #6: 0x0000000184085220 libsystem_pthread.dylib`_pthread_body + 272
    frame #7: 0x0000000184085110 libsystem_pthread.dylib`_pthread_start + 292
    frame #8: 0x0000000184083b10 libsystem_pthread.dylib`thread_start + 4
  thread #51
    frame #0: 0x0000000183ee5d84 libsystem_kernel.dylib`__workq_kernreturn + 8
    frame #1: 0x0000000184083eb4 libsystem_pthread.dylib`_pthread_wqthread + 928
    frame #2: 0x0000000184083b08 libsystem_pthread.dylib`start_wqthread + 4

**Comment by welljsjs** [comment]
Feel free to reopen if this is still reproducible.
