### ISSUE TITLE
Crash when user lock the phone

### ISSUE THREAD

**Issue by aleksandrach** [chebur/pjsip#69]
PJSIP is crashing when the app is put from foreground to background state. When the user lock the phone, in applicationWillResignActive I call pjsua_set_no_snd_dev() and then in applicationDidBecomeActive pjsua_set_snd_dev(0,0). Sometimes it crashes on this line with error pj_mutex_lock and PJSUA_LOCK. I am using version 2.5.5.6.

**Comment by welljsjs** [comment]
If it still doesn't work with the latest version, try this out: https://trac.pjsip.org/repos/wiki/Getting-Started/iPhone#bg-call.
