### ISSUE TITLE
Codec encode() error: Codec frame is too short (PJMEDIA_CODEC_EFRMTOOSHORT) [err:220082]

### ISSUE THREAD

**Issue by richnayay** [chebur/pjsip#70]
getting Codec encode() error: Codec frame is too short (PJMEDIA_CODEC_EFRMTOOSHORT) [err:220082]
after 200 ok at sip server
after ack at sip client
trying for stereo instead on mono
by following the blog and changing pjsua_media_config.channel_count to 2
https://blog.pjsip.org/2008/03/31/doing-it-in-stereo/

payload type: 10 | L16 | audio | 2 | 44100

is there any other changes that i need.

**Comment by jaredhagel** [comment]
I see the same problem in PJSIP 2.10. This bug can be repeated by running streamutil.c with the following arguments: 
--remote=224.0.0.0:4000 --play-file C:\pjproject-2.9\pjsip-apps\bin\samples\i386-win32-vc14-debug\file_example_Test_44_1.wav --codec  L16/44100/2.

Can this bug be reopened?
