### ISSUE TITLE
the question about silence detector (SD) in python

### ISSUE THREAD

**Issue by dstch** [chebur/pjsip#73]
Hello, I have a problem that I hope you'll find a solution.
I use pjsip and python to programming a soft phone.
I want to do the following:

1) Detect the voice

2) Start a recording to a wav file

3) Detect the end of voice

4) Close the wav file

I find there is Voice Activity Detector (VAD) or Silence Detector (SD) in pjsip, but I only find a variable to disable VAD or SD, I don't know how to use it in python.

please help me, thank you!

**Comment by welljsjs** [comment]
Be sure that you're reporting the issue to the correct repository and it is related to this repository and not to the [official pjsip repository](https://git.pjsip.org/gitpub/pjproject).

> I use pjsip and python to programming a soft phone.
This doesn't sound like you're using [this repo published Cocoapods](https://cocoapods.org/pods/pjsip), are you?

**Comment by dstch** [comment]
I get pjsip from https://www.pjsip.org/  and read the tutorial from https://trac.pjsip.org/repos/wiki/Python_SIP_Tutorial , maybe I make a mistake, please forgive my bother.
