### ISSUE TITLE
library not found for -lopus

### ISSUE THREAD

**Issue by iosparesh** [chebur/pjsip#74]
library not found for -lopus Error when installing pod pjsip 2.9 in objective c

**Comment by iosparesh** [comment]
Hello all,
I found the solution searching a lot.
install one more pod with
  pod 'pjsip'
  pod 'libopus'
Build successfully.

**Comment by armandzwan** [comment]
If I try to do that I get this error:

> 'libopus' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.

**Comment by welljsjs** [comment]
#84 mentions a similar problem and was fixed by #85
