### ISSUE TITLE
Registration URI issue

### ISSUE THREAD

**Issue by rccess** [chebur/pjsip#76]
Hello all 

I am facing a different kind of problem

my SIP provider getting registered with sip.conf

![image](https://user-images.githubusercontent.com/32220165/61198001-554fc400-a6f5-11e9-8826-de25ffb1857b.png)

but when i am doing same configuration in kamailio with PJSIP 

sip registry getting timeout

![image](https://user-images.githubusercontent.com/32220165/61198012-6993c100-a6f5-11e9-9225-7f58a41f7161.png)

below the sip configuration which i am using in sip.conf and getting registered
------------------------------------------------------------------------------------------

[general]

;register => +911XXXXX12100:XXX56:+911XXXX2100@dxxxhi.rexxxxeims.in/91141xxxxx2100

register => +9114xxxxx100@xxxhi.relxxxims.in:1xxxxxx56:+9114xxxxx100@dxxxxhi.relixxxms.in@10.237.252.225/+911xxxxx2100

username=+91xxx4xxx00
secret=xxxxxx56
type=friend
host=dxxxxxhi.rxxxxxxms.in
dtmfmode=rfc2833
nat=no
canreinvite=no
fromuser=+911xxxxxx100
disallow=all
allow=ulaw
allow=alaw
allow=gsm
context=default
defaultexpiry = 1900

**Comment by iosparesh** [comment]
Hello Chebur/Pjsip,

Just a guess , May be your server time is not updated.
