### ISSUE TITLE
PJSIP custom registration string

### ISSUE THREAD

**Issue by rccess** [chebur/pjsip#77]
Hello all ,

i have issue with the registration due to not correct format of PJSIP string

register => +91xxxxxxxx2100@dxxxi.rexxxxxxxxxms.in:12xxx456:+91xxxxxxxx2100@dxxxi.rexxxxxxxxxms.in@10.237.252.225/+91xxxxxxxx2100

and my voip provider only accept registration with the above string 

need some advice

how to fetch current pjsip string requested to voip provider 

and how to set above given string 

please advice

thanks

**Comment by welljsjs** [comment]
You've opened two reports within one week. 

You're not using the official issue/bug report template (- quite the opposite - what do you think that large green button `Issue/Bug report -> Get Started` is for?)

You basically show zero effort in providing a detailed, structured report. 

Why do you expect us to answer? @rccess
