### ISSUE TITLE
Win32 pjsip set log path include chinese name can't create log file 

### ISSUE THREAD

**Issue by xiaoluweiba** [chebur/pjsip#79]
compile pjsip-2.5.1 use VS 2015;

1. set callback function:

cfg->log_cfg.cb = &log_writer;

2. set pjlib support UNICODE
```
static void log_writer(int level, const char *data, int len)
{
	pj_status_t status;
	pj_ssize_t writelen = 0;
	pj_oshandle_t fd= NULL;

	status = pj_file_open(NULL, "D:\\testpjsiplog\\中文--log\\pjsip.log", PJ_O_WRONLY | PJ_O_APPEND, &androidfd);
		if (status == PJ_SUCCESS && fd) {
			writelen = len;
			status = pj_file_write(fd, data, &writelen);
			pj_file_close(fd);
		}
	}
}
```

3. If I change log path to D:\\testpjsiplog\\enligsh--log\\pjsip.log will be OK

can you give me some advice, Thank you very much

**Comment by welljsjs** [comment]
Hey @xiaoluweiba, would you mind filling out the official template for reporting issues/bugs/questions?

That makes things a lot easier for everyone.

Please also note that pjsip 2.5.1 is outdated. 

> can you give me some advice, Thank you very much

Could you elaborate a little and provider more information? What's your question and how is it related to this project?
