### ISSUE TITLE
Want to enable G729 codec in PJSIP

### ISSUE THREAD

**Issue by Arslan007** [chebur/pjsip#8]
Hi,
I want to enable G729 codec in PJSIP for iOS architectures like armv7, armv7s and x64.
Your help will be much appreciated. I am struggling from last like 2 weeks.

Regards,
Arslan

**Comment by shehrazjazib** [comment]
Intel IPP has left the support of G729 codec. so please guide me, what should i do to integrate G729 codec with latest pjsip

**Comment by Arslan007** [comment]
@shehrazjazib You need to use open source version of G729.

**Comment by shehrazjazib** [comment]
@Arslan007 can u please elaborate your statement more ? I tried many patches from Csipcimple, but didn't get success .

**Comment by Arslan007** [comment]
@shehrazjazib  You can use G729 from Doubango Source or Linphone Source.
