### ISSUE TITLE
Build errors after updating to 2.9

### ISSUE THREAD

**Issue by armandzwan** [chebur/pjsip#84]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the README and found no answer 
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository as it is related to this repository and not to the [official pjsip repository](https://www.pjsip.org)

# Expected Behavior

App to build normally after updating to version 2.9

# Current Behavior

I get build errors

# Failure Information (for bugs)

> Undefined symbols for architecture arm64:
>   "_opus_decode", referenced from:
>       _codec_decode in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>       _codec_recover in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>   "_opus_repacketizer_out", referenced from:
>       _codec_encode in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>   "_opus_repacketizer_get_nb_frames", referenced from:
>       _codec_parse in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>       _codec_encode in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>   "_opus_encode", referenced from:
>       _codec_encode in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>   "_opus_encoder_get_size", referenced from:
>       _codec_open in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>   "_opus_decoder_get_size", referenced from:
>       _codec_open in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>   "_opus_repacketizer_out_range", referenced from:
>       _codec_parse in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>   "_opus_repacketizer_get_size", referenced from:
>       _codec_open in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>   "_opus_repacketizer_cat", referenced from:
>       _codec_parse in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>       _codec_encode in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>   "_opus_encoder_ctl", referenced from:
>       _codec_open in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>       _codec_modify in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>   "_opus_encoder_init", referenced from:
>       _codec_open in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>   "_opus_decoder_init", referenced from:
>       _codec_open in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>   "_opus_packet_get_nb_samples", referenced from:
>       _codec_parse in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>   "_opus_repacketizer_init", referenced from:
>       _codec_open in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>       _codec_parse in libpjmedia-codec-apple-darwin_ios.a(opus.o)
>       _codec_encode in libpjmedia-codec-apple-darwin_ios.a(opus.o)
> ld: symbol(s) not found for architecture arm64

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Update project with v2.8 to 2.9
2. Try to build

## Context

* Xcode Version: 10.3
* Platform and architecture building for: iOS 9.0 and higher, arm64 arm64e armv7 armv7s
* Operating System: Mac OS 10.14.6

**Comment by welljsjs** [comment]
Hey @armandzwan,

thanks for using our issue templates!

Would you be so kind and provide me 1.) your `Podfile` and 2.) some more information or a short code extract how you've been using/integrating this framework (e.g. are you using a `Bridging-Header`)?

**Comment by armandzwan** [comment]
My podfile:
```
platform :ios, '9.0'
use_frameworks!

target '...' do
  pod 'pjsip'
end
```

**Comment by welljsjs** [comment]
On it. Reproducible when calling any pjsua function from Swift. 

I'll provide a fix asap.

Please note that it may take a few days until we come out with a fix for this. 

This is likely an issue with the Podspec file.

**Comment by welljsjs** [comment]
@chebur Would you update the pod with `2.9.0.2`?

**Comment by chebur** [comment]
done
