### ISSUE TITLE
Cannot setHold for incoming call in PJSUA2

### ISSUE THREAD

**Issue by jiahao-shen** [chebur/pjsip#91]
When using pjsua2 in python3.6, cannot setHold from incoming call?
It catch error: Cannot hold call that is not confirmed.
Even if I answer the call, it doesn’t confirm.
So how to confirm the incoming call?
Thank you very much.

**Comment by welljsjs** [comment]
https://github.com/chebur/pjsip/blob/master/README.md#features

This is a build for iOS. Feel free to reopen if necessary.
