### ISSUE TITLE
How to use library in ios objective-c

### ISSUE THREAD

**Issue by benedictcontawe** [chebur/pjsip#92]
How to call in ios objective-c
Do you have tutorial and detailed code to to this. Many thanks in advance

**Comment by welljsjs** [comment]
Theres not really a "tutorial" in Objective-C I suspect. But we do have an example folder in the repo root. Though they might be a little out of date and you probably can't just copy & paste them, they should give you an overall idea. 

Or just have a look at the official `pjsip` examples - the most applicable of which I'd think is this one: https://www.pjsip.org/pjsip/docs/html/page_pjsip_sample_simple_pjsuaua_c.htm
