### ISSUE TITLE
Issue at running of ./build.sh

### ISSUE THREAD

**Issue by krishnastvSMSC** [chebur/pjsip#96]
Hello Team, while build this library got and compile stuck.Please check the below screens for reference. Help us to resolve this issue.
![Screenshot 2020-06-05 at 4 38 54 PM](https://user-images.githubusercontent.com/45424351/83870229-83922400-a74b-11ea-9d70-d56845b58985.png)
![Screenshot 2020-06-05 at 4 39 12 PM](https://user-images.githubusercontent.com/45424351/83870238-87be4180-a74b-11ea-9843-0ab3b64d3728.png)

Thanks in advance

**Comment by welljsjs** [comment]
Hi, I assume you're building on macOS 10.15.5? Do you have the Xcode dev tools installed? 

```
xcode-select --install
```

**Comment by krishnastvSMSC** [comment]
Helllo,
Yes am running on macOS 10.15.5. Xcode development tool and command line tool also installed correctly. I have clang, gcc too. Still am getting same issue

**Comment by welljsjs** [comment]
Can you please post the output of `gcc -v` and `clang -v`?

**Comment by krishnastvSMSC** [comment]
Hello , find the attachment for reference 
![Screenshot 2020-06-08 at 10 52 50 AM](https://user-images.githubusercontent.com/45424351/83995178-56758980-a976-11ea-9152-bbfde34e1379.png)

I am unable to build the app.
