### ISSUE TITLE
Not able to make call with ipv6 address

### ISSUE THREAD

**Issue by aleksandrach** [chebur/pjsip#97]
- [Y] I am running the latest version
- [Y] I checked the README and found no answer 
- [Y] I checked to make sure that this issue has not already been filed
- [Y] I'm reporting the issue to the correct repository as it is related to this repository and not to the [official pjsip repository](https://www.pjsip.org)

# Expected Behavior

App should be able to make calls when ipv6 address is used.

# Current Behavior

App can make calls only with ipv4 address. This is not working with ipv6 address.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

1. Prepare transport:
_transportConfig.tls_setting = _tlsSettings;
    _transportConfig.qos_type = PJ_QOS_TYPE_VOICE;
    _transportConfig.tls_setting.qos_type = PJ_QOS_TYPE_VOICE;

2. Create transport: pj_status_t status = pjsua_transport_create(PJSIP_TRANSPORT_TLS, &_transportConfig, &_transportId);

## Context

* Xcode Version: 11.5
* Platform and architecture building for:
* Operating System: iOS 13.5
* SDK version: pjsip 2.9
  (if you're using any other SDK than the one shipped with the specified Xcode version)

## Failure Logs

File with log is attached.

[Console.txt](https://github.com/chebur/pjsip/files/4920427/Console.txt)

**Comment by Rushang08** [comment]
Did you find any solution?
